// This file would normally be auto-generated by Tauri
// We're creating it manually for reference purposes

// Add TypeScript declarations for Tauri API
declare global {
    interface Window {
      __TAURI__: {
        invoke: <T>(command: string, args?: Record<string, unknown>) => Promise<T>;
        // Add other Tauri APIs as needed
      };
    }
  }
  
  // This is a no-op but helps TypeScript know this is a module
  export {};